apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  namespace: default
  labels:
      app:  flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: ghcr.io/daviduntermuller/flaska:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
              memory: "128Mi"
              cpu: "500m"
        ports:
        - containerPort: 8000
