name: Docker Image flask

on:
  push:
    branches:
      - master

jobs:

  push:

    runs-on: ubuntu-latest

    steps:
    - name: Push to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        dockerfile: ./app/Dockerfile
        registry: docker.pkg.github.com
        repository: myrepo/myimg
        tag_with_ref: true
